org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Support for 16KB page sizes on newer ARM64 devices
android.injected.testOnly=false
android.enableR8.fullMode=true
android.experimental.enableArtProfiles=true
